# Generated by Django 2.2.16 on 2020-11-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
