# Generated by Django 2.2.16 on 2020-12-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201129_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile',
            new_name='username',
        ),
    ]
